# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

default: &defaults
  docker:
    - image: circleci/node:7.10

  working_directory: ~/repo


jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  release:
    <<: *defaults

    steps:
      - checkout

      - run:
          command: |
            if [[ $VERSION ]]; then
              sudo npm install --global np
              echo 'registry=https://registry.npmjs.org/:_authToken=${NPM_TOKEN}' > $HOME/.npmrc
              np $VERSION
            else
              echo "Release skipped. Use this to perform a release:
              curl -X POST -H \"Content-Type: application/json\" -d '{
                  \"build_parameters\": {
                      \"CIRCLE_JOB\": \"release\",
                      \"VERSION\": \"1.1.1\"
                  }
              }' \"https://circleci.com/api/v1.1/project/github/ORG/PROJECT/tree/master?circle-token=TOKEN\"
              "
            fi

workflows:
  version: 2
  main:
    jobs:
      - build