# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

default: &defaults
  docker:
    - image: circleci/node:9.2

  working_directory: ~/repo


jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test

  release:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Verify parameters
          command: |
            if [[ $VERSION ]]; then
              if [[ ! $GIT_USER_EMAIL || ! $GIT_USER_NAME ]]; then
                echo 'Must set GIT_USER_EMAIL and GIT_USER_NAME'
                exit 1
              fi
            else
              echo "Skipping release build since VERSION is not set"
              exit 1
            fi

      - run: yarn install --frozen-lockfile

      - run: yarn test

      - run:
          name: configure git
          command: |
            git config --global user.email "$GIT_USER_EMAIL"
            git config --global user.name "$GIT_USER_NAME"

      - run: yarn version --new-version $VERSION

      - run: yarn build

      - run:
          name: yarn publish
          command: |
            echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > $HOME/.npmrc
            yarn publish --new-version $VERSION

      - run: git push --follow-tags


workflows:
  version: 2
  main:
    jobs:
      - build